import React, { useEffect } from 'react';
import { Affiliate, Form, Navbar } from '../components';
import { useInvalidUrlRoutes } from '../security/helpers';
import { Videos, About, Header, Pictures, Testimonials, Blog } from '../containers';
import galleryPictures from '../data/gallery-pictures';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Aos from 'aos';
import 'aos/dist/aos.css';

const Home = () => {
  useInvalidUrlRoutes();

  useEffect(() => {
    Aos.init({ duration: 2500 });
  }, []);

  return (
      <div className={"Home"}  id={"home"} data-aos={"fade"}>
          <Head>
              <title>Cyril Junior Dim</title>
              <meta name="description" content="The professional website of Championship Speaker Cyril Junior Dim. Useful for coaching, hiring a speaker for your event or other such bookings."/>
              <meta property="og:title" content="Cyril Junior Dim's Website"/>
              <meta property="og:description" content="The professional website of Championship Speaker Cyril Junior Dim.
              Useful for coaching, hiring a speaker for your event or other such bookings."/>
              <meta property="og:url" content="https://cyriljuniordim.com/"/>
              <meta property="og:type" content="website"/>
              <link rel="icon" href="/assets/logos/logo-white.png" />
          </Head>
        <div className={styles.homeImg} style={{backgroundImage: `url(/assets/img/home-main-image.png)`, backgroundSize: 'cover'}}>
          <div className={styles.homeNav}>
            <Navbar />
          </div>
          <Header />
        </div>
        <div className={"affiliates"} data-aos={"fade-up"}>
          <Affiliate />
        </div>
        <div className={"about-short"} id={"about"}>
          <About />
        </div>
        <Videos />
        <div className={"testimonials-container"} data-aos={"flip-right"}>
          <Testimonials />
        </div>
        <div className={styles.formContainer}>
          <div className={`${styles.form} section__padding`} data-aos={"slide-left"}>
            <div className={styles.cyrilWebsite__formText}>
              <p>
                Subscribe to receive updates from Cyril and get his article “The Story of Ndini”.
              </p>
            </div>
            <Form />
          </div>
        </div>
        <div className={`${styles.galleryContainer} section__padding`} data-aos={"fade-up"}>
          <Pictures galleryImages={galleryPictures} />
        </div>
        <Blog />
      </div>
  );
}

export default Home;



// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
//
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//
//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>
//
//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>
//
//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>
//
//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//
//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
